/*CREATE DATABASE bd_mundo;
USE bd_mundo;

CREATE TABLE tb_paises (
  id_pais INT AUTO_INCREMENT PRIMARY KEY,
  nm_pais VARCHAR(100) NOT NULL,
  nm_continente VARCHAR(50),
  qt_populacao INT,
  nm_idioma VARCHAR(50)
);

CREATE TABLE tb_cidades (
  id_cidade INT AUTO_INCREMENT PRIMARY KEY,
  nm_nome VARCHAR(100) NOT NULL,
  qt_populacao INT,
  id_pais INT,
  FOREIGN KEY (id_pais) REFERENCES tb_paises(id_pais)
);
*/

-- MySQL Script generated by MySQL Workbench
-- sab 09 nov 2025 20:10
-- Model: CRUD Mundo  |  Version: 1.0
-- ---------------------------------------

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_mundo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `bd_mundo`;

-- -----------------------------------------------------
-- Table: tb_pais
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nm_pais` VARCHAR(100) NOT NULL,
  `nm_continente` VARCHAR(50),
  `qt_populacao` INT,
  `nm_idioma` VARCHAR(50),
  `nm_capital` VARCHAR(80),
  `url_bandeira` VARCHAR(255),
  PRIMARY KEY (`id_pais`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: tb_cidade
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nm_cidade` VARCHAR(100) NOT NULL,
  `qt_populacao` INT,
  `vl_temperatura` DECIMAL(5,2),
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_tb_cidade_tb_pais_idx` (`id_pais` ASC),
  CONSTRAINT `fk_tb_cidade_tb_pais`
    FOREIGN KEY (`id_pais`)
    REFERENCES `tb_pais` (`id_pais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: tb_usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nm_usuario` VARCHAR(80) NOT NULL,
  `nm_email` VARCHAR(80) NOT NULL UNIQUE,
  `cd_senha` VARCHAR(64) NOT NULL,
  `dt_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: tb_categoria_continente (opcional)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_categoria_continente` (
  `id_categoria_cont` INT NOT NULL AUTO_INCREMENT,
  `nm_categoria_cont` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria_cont`)
) ENGINE = InnoDB;

-- Relacionamento com tb_pais
ALTER TABLE `tb_pais`
  ADD COLUMN `id_categoria_cont` INT NULL,
  ADD CONSTRAINT `fk_tb_pais_tb_categoria_continente`
  FOREIGN KEY (`id_categoria_cont`)
  REFERENCES `tb_categoria_continente` (`id_categoria_cont`)
  ON DELETE SET NULL
  ON UPDATE CASCADE;

-- -----------------------------------------------------
-- Inserts iniciais
-- -----------------------------------------------------
INSERT INTO `tb_usuario` (`nm_usuario`, `nm_email`, `cd_senha`)
VALUES ('Laura Letícia', 'laura@email.com', SHA2('123', 256));

INSERT INTO `tb_categoria_continente` (`nm_categoria_cont`) VALUES
('América do Sul'),
('América do Norte'),
('Europa'),
('Ásia'),
('África'),
('Oceania'),
('Antártida');

-- -----------------------------------------------------
-- Países de exemplo (para teste do mapa)
-- -----------------------------------------------------
INSERT INTO `tb_pais` (`nm_pais`, `nm_continente`, `qt_populacao`, `nm_idioma`, `nm_capital`, `url_bandeira`)
VALUES
('Brasil', 'América do Sul', 215000000, 'Português', 'Brasília', 'https://flagcdn.com/w320/br.png'),
('Estados Unidos', 'América do Norte', 331000000, 'Inglês', 'Washington D.C.', 'https://flagcdn.com/w320/us.png'),
('França', 'Europa', 67000000, 'Francês', 'Paris', 'https://flagcdn.com/w320/fr.png'),
('Japão', 'Ásia', 126000000, 'Japonês', 'Tóquio', 'https://flagcdn.com/w320/jp.png'),
('Austrália', 'Oceania', 26000000, 'Inglês', 'Camberra', 'https://flagcdn.com/w320/au.png');

-- -----------------------------------------------------
-- Cidades de exemplo
-- -----------------------------------------------------
INSERT INTO `tb_cidade` (`nm_cidade`, `qt_populacao`, `vl_temperatura`, `id_pais`)
VALUES
('São Paulo', 12000000, 25.5, 1),
('Nova York', 8500000, 20.0, 2),
('Paris', 2200000, 18.2, 3),
('Tóquio', 13900000, 22.5, 4),
('Sydney', 5300000, 23.0, 5);

-- -----------------------------------------------------
-- Teste de consulta
-- -----------------------------------------------------
SELECT * FROM `tb_pais`;
SELECT * FROM `tb_cidade`;
SELECT * FROM `tb_usuario`;

-- -----------------------------------------------------
-- Restaurar configurações originais
-- -----------------------------------------------------
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
